animal = [
    {"name": "Lion",
     "location": "Africa, India",
     "characteristics": "large cat, known for its roar and mane",
     "longevity": 15},
    {"name": "Elephant",
     "location": "Africa, Asia",
     "characteristics": "largest land animal, long trunk, tusks",
     "longevity": 60},
    {"name": "Tiger",
     "location": "Asia",
     "characteristics": "largest cat species, distinctive stripes",
     "longevity": 15},
    {"name": "Giraffe",
     "location": "Africa",
     "characteristics": "tallest mammal, long neck",
     "longevity": 25},
    {"name": "Zebra",
     "location": "Africa",
     "characteristics": "equid with distinctive black and white stripes",
     "longevity": 25},
    {"name": "Panda",
     "location": "China",
     "characteristics": "bear known for its black and white fur, eats bamboo",
     "longevity": 20},
    {"name": "Polar Bear",
     "location": "Arctic",
     "characteristics": "large bear adapted to cold environments, white fur",
     "longevity": 25},
    {"name": "Kangaroo",
     "location": "Australia",
     "characteristics": "marsupial with powerful hind legs, hops",
     "longevity": 6},
    {"name": "Koala",
     "location": "Australia",
     "characteristics": "arboreal marsupial, eats eucalyptus leaves",
     "longevity": 13},
    {"name": "Wolf",
     "location": "North America, Eurasia",
     "characteristics": "canine known for howling, lives in packs",
     "longevity": 8},
    {"name": "Fox",
     "location": "Worldwide",
     "characteristics": "omnivorous mammal, known for its cunning",
     "longevity": 5},
    {"name": "Bear",
     "location": "North America, Eurasia",
     "characteristics": "large omnivorous mammal, hibernates",
     "longevity": 25},
    {"name": "Hippopotamus",
     "location": "Africa",
     "characteristics": "large, semi-aquatic mammal, aggressive",
     "longevity": 40},
    {"name": "Rhinoceros",
     "location": "Africa, Asia",
     "characteristics": "large, herbivorous mammal with a horn",
     "longevity": 40},
    {"name": "Gorilla",
     "location": "Africa",
     "characteristics": "largest primate, intelligent, strong",
     "longevity": 40},
    {"name": "Chimpanzee",
     "location": "Africa",
     "characteristics": "intelligent primate, known for tool use",
     "longevity": 50},
    {"name": "Orangutan",
     "location": "Borneo, Sumatra",
     "characteristics": "arboreal ape, long reddish-brown hair",
     "longevity": 40},
    {"name": "Dolphin",
     "location": "Worldwide oceans",
     "characteristics": "aquatic mammal, highly intelligent, social",
     "longevity": 30},
    {"name": "Whale",
     "location": "Worldwide oceans",
     "characteristics": "largest mammal, aquatic, various species",
     "longevity": 70},
    {"name": "Shark",
     "location": "Worldwide oceans",
     "characteristics": "cartilaginous fish, apex predator",
     "longevity": 30},
    {"name": "Penguin",
     "location": "Southern Hemisphere",
     "characteristics": "flightless bird, adapted to aquatic life",
     "longevity": 20},
    {"name": "Eagle",
     "location": "Worldwide",
     "characteristics": "large bird of prey, excellent eyesight",
     "longevity": 20},
    {"name": "Owl",
     "location": "Worldwide",
     "characteristics": "nocturnal bird of prey, excellent hearing",
     "longevity": 15},
    {"name": "Snake",
     "location": "Worldwide",
     "characteristics": "legless reptile, some are venomous",
     "longevity": 10},
    {"name": "Crocodile",
     "location": "Africa, Asia, Americas, Australia",
     "characteristics": "large semi-aquatic reptile, powerful jaws",
     "longevity": 70},
    {"name": "Alligator",
     "location": "North America, China",
     "characteristics": "large semi-aquatic reptile, rounded snout",
     "longevity": 50},
    {"name": "Turtle",
     "location": "Worldwide",
     "characteristics": "reptile with a hard shell, lives on land or in water",
     "longevity": 50},
    {"name": "Frog",
     "location": "Worldwide",
     "characteristics": "amphibian, jumps, lives near water",
     "longevity": 5},
    {"name": "Lizard",
     "location": "Worldwide",
     "characteristics": "scaly reptile, some can change color",
     "longevity": 10},
    {"name": "Parrot",
     "location": "Tropical regions",
     "characteristics": "colorful bird, can mimic human speech",
     "longevity": 50},
    {"name": "Peacock",
     "location": "India, Sri Lanka",
     "characteristics": "bird known for its elaborate tail feathers",
     "longevity": 20},
    {"name": "Flamingo",
     "location": "Americas, Africa, Asia, Europe",
     "characteristics": "pink wading bird, stands on one leg",
     "longevity": 30},
    {"name": "Koala",
     "location": "Australia",
     "characteristics": "arboreal marsupial, eats eucalyptus leaves",
     "longevity": 13},
    {"name": "Cheetah",
     "location": "Africa",
     "characteristics": "fastest land animal",
     "longevity": 12},
    {"name": "Jaguar",
     "location": "Americas",
     "characteristics": "large spotted cat, powerful bite",
     "longevity": 15},
    {"name": "Leopard",
     "location": "Africa, Asia",
     "characteristics": "large spotted cat, agile climber",
     "longevity": 15},
    {"name": "Puma (Cougar)",
     "location": "Americas",
     "characteristics": "large cat, solitary, adaptable",
     "longevity": 15},
    {"name": "Sloth",
     "location": "Central and South America",
     "characteristics": "slow-moving arboreal mammal",
     "longevity": 20},
    {"name": "Armadillo",
     "location": "Americas",
     "characteristics": "mammal with a bony armored shell",
     "longevity": 10},
    {"name": "Pangolin",
     "location": "Africa, Asia",
     "characteristics": "scaly anteater, curls into a ball for defense",
     "longevity": 10},
    {"name": "Platypus",
     "location": "Australia",
     "characteristics": "monotreme, duck-billed, lays eggs",
     "longevity": 12},
    {"name": "Echidna",
     "location": "Australia, New Guinea",
     "characteristics": "spiny anteater, monotreme, lays eggs",
     "longevity": 15},
    {"name": "Lemur",
     "location": "Madagascar",
     "characteristics": "primate, large eyes, long tail",
     "longevity": 18},
    {"name": "Red Panda",
     "location": "Himalayas, Southwest China",
     "characteristics": "arboreal mammal, reddish-brown fur, bushy tail",
     "longevity": 10},
    {"name": "Fennec Fox",
     "location": "North Africa",
     "characteristics": "small fox, large ears, nocturnal",
     "longevity": 10},
    {"name": "Meerkat",
     "location": "Southern Africa",
     "characteristics": "small mongoose, stands upright, lives in colonies",
     "longevity": 10},
    {"name": "Ostrich",
     "location": "Africa",
     "characteristics": "largest flightless bird, fast runner",
     "longevity": 50},
    {"name": "Toucan",
     "location": "Central and South America",
     "characteristics": "colorful bird, large, distinctive bill",
     "longevity": 20},
    {"name": "Hummingbird",
     "location": "Americas",
     "characteristics": "smallest bird, hovers, rapid wing beats",
     "longevity": 5},
    {"name": "Pufferfish",
     "location": "Tropical and subtropical waters",
     "characteristics": "fish that inflates its body when threatened, toxic",
     "longevity": 10}
]


