image:
  file: .gitpod.Dockerfile

tasks:
  - command: >
      jupyter lab
      --ServerApp.allow_origin_regex='.*gitpod.io$'
      --ServerApp.allow_remote_access=True
      --ServerApp.allow_root=True
      --ServerApp.allow_hosts='*'
  