animal = [
    {"name": "Cheetah",
     "location": "Africa",
     "characteristics": "fastest land animal",
     "longevity": 12},
    {"name": "Kangaroo",
     "location": "Australia",
     "characteristics": "powerful hind legs, marsupial",
     "longevity": 6},
    {"name": "Polar Bear",
     "location": "Arctic",
     "characteristics": "thick fur and blubber for cold, apex predator",
     "longevity": 25},
    {"name": "Elephant",
     "location": "Africa, Asia",
     "characteristics": "largest land animal, long trunk",
     "longevity": 60},
    {"name": "Blue Whale",
     "location": "All Oceans",
     "characteristics": "largest animal on Earth, filter feeder",
     "longevity": 90},
    {"name": "Lion",
     "location": "Africa, India",
     "characteristics": "king of the jungle, social predators",
     "longevity": 15},
    {"name": "Panda",
     "location": "Asia",
     "characteristics": "bamboo diet, distinctive black and white fur",
     "longevity": 20},
    {"name": "Giraffe",
     "location": "Africa",
     "characteristics": "tallest mammal, long neck",
     "longevity": 25},
    {"name": "Penguin",
     "location": "Antarctica, Southern Hemisphere",
     "characteristics": "flightless bird, excellent swimmer",
     "longevity": 15},
    {"name": "Tiger",
     "location": "Asia",
     "characteristics": "striped coat, solitary hunter",
     "longevity": 18},
    {"name": "Gorilla",
     "location": "Africa",
     "characteristics": "largest primate, intelligent",
     "longevity": 40},
    {"name": "Dolphin",
     "location": "All Oceans",
     "characteristics": "highly intelligent marine mammal, uses echolocation",
     "longevity": 20},
    {"name": "Wolf",
     "location": "North America, Eurasia",
     "characteristics": "highly social, howl to communicate",
     "longevity": 8},
    {"name": "Eagle",
     "location": "Various (North America, Eurasia, Africa)",
     "characteristics": "apex aerial predator, keen eyesight",
     "longevity": 20},
    {"name": "Snake",
     "location": "All Continents (except Antarctica)",
     "characteristics": "legless reptile, some are venomous",
     "longevity": 10},
    {"name": "Crocodile",
     "location": "Africa, Asia, Americas, Australia",
     "characteristics": "ancient reptile, powerful bite",
     "longevity": 70},
    {"name": "Chimpanzee",
     "location": "Africa",
     "characteristics": "closest living relatives to humans, use tools",
     "longevity": 50},
    {"name": "Octopus",
     "location": "All Oceans",
     "characteristics": "highly intelligent invertebrate, camouflage master",
     "longevity": 3},
    {"name": "Grizzly Bear",
     "location": "North America",
     "characteristics": "large omnivore, powerful claws",
     "longevity": 25},
    {"name": "Zebra",
     "location": "Africa",
     "characteristics": "distinctive black and white stripes, social herds",
     "longevity": 20},
    {"name": "Hippopotamus",
     "location": "Africa",
     "characteristics": "large semi-aquatic mammal, highly territorial",
     "longevity": 45},
    {"name": "Rhinoceros",
     "location": "Africa, Asia",
     "characteristics": "large herbivore, distinctive horn(s)",
     "longevity": 40},
    {"name": "Ostrich",
     "location": "Africa",
     "characteristics": "largest flightless bird, fastest runner on two legs",
     "longevity": 50},
    {"name": "Komodo Dragon",
     "location": "Asia (Indonesia)",
     "characteristics": "largest living lizard, venomous bite",
     "longevity": 30},
    {"name": "Puma (Cougar)",
     "location": "Americas",
     "characteristics": "solitary hunter, adaptable to various habitats",
     "longevity": 10},
    {"name": "Deer",
     "location": "Various (North America, Eurasia, etc.)",
     "characteristics": "herbivore, antlers shed annually",
     "longevity": 8},
    {"name": "Fox",
     "location": "All Continents (except Antarctica)",
     "characteristics": "cunning omnivore, adaptable",
     "longevity": 5},
    {"name": "Squirrel",
     "location": "All Continents (except Antarctica & Australia)",
     "characteristics": "agile arboreal rodent, gathers nuts",
     "longevity": 6},
    {"name": "Bat",
     "location": "All Continents (except Antarctica)",
     "characteristics": "only flying mammal, nocturnal",
     "longevity": 20},
    {"name": "Rabbit",
     "location": "All Continents (except Antarctica)",
     "characteristics": "fast breeder, herbivore",
     "longevity": 8},
    {"name": "Owl",
     "location": "All Continents (except Antarctica)",
     "characteristics": "nocturnal bird of prey, silent flight",
     "longevity": 15},
    {"name": "Kookaburra",
     "location": "Australia",
     "characteristics": "known for its distinctive \"laughing\" call",
     "longevity": 20},
    {"name": "Bald Eagle",
     "location": "North America",
     "characteristics": "national bird of the USA, keen eyesight",
     "longevity": 20},
    {"name": "Manatee",
     "location": "Americas, Africa",
     "characteristics": "gentle marine mammal, herbivore",
     "longevity": 40},
    {"name": "Sloth",
     "location": "South America",
     "characteristics": "slowest mammal, arboreal",
     "longevity": 20},
    {"name": "Piranha",
     "location": "South America",
     "characteristics": "carnivorous freshwater fish, sharp teeth",
     "longevity": 10},
    {"name": "Anaconda",
     "location": "South America",
     "characteristics": "largest snake by mass, non-venomous constrictor",
     "longevity": 10},
    {"name": "Armadillo",
     "location": "Americas",
     "characteristics": "bony armor plating, digger",
     "longevity": 10},
    {"name": "Beaver",
     "location": "North America, Europe, Asia",
     "characteristics": "builds dams and lodges, semi-aquatic rodent",
     "longevity": 10},
    {"name": "Camel",
     "location": "Africa, Asia",
     "characteristics": "humps store fat, tolerant to desert conditions",
     "longevity": 40},
    {"name": "Coyote",
     "location": "North America",
     "characteristics": "adaptable canid, often seen in urban areas",
     "longevity": 10},
    {"name": "Flamingo",
     "location": "Americas, Africa, Asia, Europe",
     "characteristics": "pink feathers, filters food from water",
     "longevity": 30},
    {"name": "Gazelle",
     "location": "Africa, Asia",
     "characteristics": "fast runner, graceful",
     "longevity": 12},
    {"name": "Hedgehog",
     "location": "Europe, Asia, Africa",
     "characteristics": "spiny mammal, rolls into a ball for defense",
     "longevity": 7},
    {"name": "Iguana",
     "location": "Americas",
     "characteristics": "herbivorous lizard, long tail",
     "longevity": 15},
    {"name": "Jaguar",
     "location": "Americas",
     "characteristics": "largest cat in the Americas, powerful bite",
     "longevity": 15},
    {"name": "Koala",
     "location": "Australia",
     "characteristics": "eucalyptus diet, marsupial",
     "longevity": 15},
    {"name": "Lemur",
     "location": "Africa (Madagascar)",
     "characteristics": "primate, large eyes, diverse species",
     "longevity": 18},
    {"name": "Meerkat",
     "location": "Africa",
     "characteristics": "social mammal, stands upright to watch for predators",
     "longevity": 10},
    {"name": "Nightingale",
     "location": "Europe, Asia, Africa",
     "characteristics": "small passerine bird, known for its powerful and beautiful song",
     "longevity": 5}
]